# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ivoice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ivoice.proto',
  package='ivoice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0civoice.proto\x12\x06ivoice\"6\n\x06Result\x12\x0f\n\x07segment\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04word\x18\x03 \x01(\t\"%\n\x07Segment\x12\r\n\x05start\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x02\"+\n\x11TranscribeRequest\x12\x16\n\x0eremoteFilePath\x18\x01 \x01(\t\"N\n\rSegmentResult\x12 \n\x07segment\x18\x01 \x01(\x0b\x32\x0f.ivoice.Segment\x12\r\n\x05label\x18\x02 \x01(\x05\x12\x0c\n\x04word\x18\x03 \x01(\t2\\\n\rIVoiceToolkit\x12K\n\x13transcribeAudioFile\x12\x19.ivoice.TranscribeRequest\x1a\x15.ivoice.SegmentResult\"\x00\x30\x01\x62\x06proto3'
)




_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='ivoice.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='ivoice.Result.segment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='ivoice.Result.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='ivoice.Result.word', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=78,
)


_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='ivoice.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='ivoice.Segment.start', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='ivoice.Segment.end', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=117,
)


_TRANSCRIBEREQUEST = _descriptor.Descriptor(
  name='TranscribeRequest',
  full_name='ivoice.TranscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remoteFilePath', full_name='ivoice.TranscribeRequest.remoteFilePath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=162,
)


_SEGMENTRESULT = _descriptor.Descriptor(
  name='SegmentResult',
  full_name='ivoice.SegmentResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='ivoice.SegmentResult.segment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='ivoice.SegmentResult.label', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='ivoice.SegmentResult.word', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=242,
)

_SEGMENTRESULT.fields_by_name['segment'].message_type = _SEGMENT
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.message_types_by_name['TranscribeRequest'] = _TRANSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['SegmentResult'] = _SEGMENTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'ivoice_pb2'
  # @@protoc_insertion_point(class_scope:ivoice.Result)
  })
_sym_db.RegisterMessage(Result)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'ivoice_pb2'
  # @@protoc_insertion_point(class_scope:ivoice.Segment)
  })
_sym_db.RegisterMessage(Segment)

TranscribeRequest = _reflection.GeneratedProtocolMessageType('TranscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSCRIBEREQUEST,
  '__module__' : 'ivoice_pb2'
  # @@protoc_insertion_point(class_scope:ivoice.TranscribeRequest)
  })
_sym_db.RegisterMessage(TranscribeRequest)

SegmentResult = _reflection.GeneratedProtocolMessageType('SegmentResult', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTRESULT,
  '__module__' : 'ivoice_pb2'
  # @@protoc_insertion_point(class_scope:ivoice.SegmentResult)
  })
_sym_db.RegisterMessage(SegmentResult)



_IVOICETOOLKIT = _descriptor.ServiceDescriptor(
  name='IVoiceToolkit',
  full_name='ivoice.IVoiceToolkit',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=244,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='transcribeAudioFile',
    full_name='ivoice.IVoiceToolkit.transcribeAudioFile',
    index=0,
    containing_service=None,
    input_type=_TRANSCRIBEREQUEST,
    output_type=_SEGMENTRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IVOICETOOLKIT)

DESCRIPTOR.services_by_name['IVoiceToolkit'] = _IVOICETOOLKIT

# @@protoc_insertion_point(module_scope)
